name: huge_icons_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage: https://arksoftwarez.com

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/huge_icons/add-01-stroke-rounded.svg
    - assets/huge_icons/add-02-stroke-rounded.svg
    - assets/huge_icons/add-circle-half-dot-stroke-rounded.svg
    - assets/huge_icons/add-circle-stroke-rounded.svg
    - assets/huge_icons/add-square-stroke-rounded.svg
    - assets/huge_icons/cancel-01-stroke-rounded.svg
    - assets/huge_icons/cancel-02-stroke-rounded.svg
    - assets/huge_icons/cancel-circle-half-dot-stroke-rounded.svg
    - assets/huge_icons/cancel-circle-stroke-rounded.svg
    - assets/huge_icons/cancel-square-stroke-rounded.svg
    - assets/huge_icons/delete-01-stroke-rounded.svg
    - assets/huge_icons/add-01-stroke-rounded.svg
    - assets/huge_icons/delete-02-stroke-rounded.svg
    - assets/huge_icons/delete-03-stroke-rounded.svg
    - assets/huge_icons/delete-04-stroke-rounded.svg
    - assets/huge_icons/delete-put-back-stroke-rounded.svg
    - assets/huge_icons/delete-throw-stroke-rounded.svg
    - assets/huge_icons/eraser-01-stroke-rounded.svg
    - assets/huge_icons/eraser-add-stroke-rounded.svg
    - assets/huge_icons/remove-01-stroke-rounded.svg
    - assets/huge_icons/remove-02-stroke-rounded.svg
    - assets/huge_icons/remove-circle-half-dot-stroke-rounded.svg
    - assets/huge_icons/remove-circle-stroke-rounded.svg
    - assets/huge_icons/remove-square-stroke-rounded.svg
    - assets/huge_icons/restore-bin-stroke-rounded.svg
    - assets/huge_icons/unavailable-stroke-rounded.svg
    - assets/huge_icons/waste-restore-stroke-rounded.svg
    - assets/huge_icons/waste-stroke-rounded.svg
    - assets/huge_icons/unavailable-stroke-rounded.svg


  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
